name: X. Build Latest
run-name: Build Latest ${{ github.ref_name }}
on:
  workflow_dispatch:

jobs:
  syncing:
    uses: ./.github/workflows/sync_fork.yml
    secrets: inherit
    
  building:
    needs: sync
    uses: ./.github/workflows/build_loop.yml
    secrets: inherit
