name: X. Build Latest
run-name: Build Latest ${{ github.ref_name }}
on:
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/sync_fork.yml 
    
  build:
    uses: ./.github/workflows/build_loop.yml
    secrets: inherit
    needs: sync
