name: X. Build Loop
run-name: Build Loop ${{ github.ref_name }}
on:
  workflow_dispatch:
  
  ## Remove the "#" sign from the beginning of the line below to get automated builds on push (code changes in your repository)
  #push:

  ## Remove the "#" sign from the beginning of the two lines below to get automated builds every two months
  #schedule:
    #- cron: '0 17 1 */2 *' # Runs at 17:00 UTC on the 1st in Jan, Mar, May, Jul, Sep and Nov.

jobs:
  secrets:
    uses: ./.github/workflows/validate_secrets.yml
    secrets: inherit
  build:
    uses: ./.github/workflows/build_loop.yml
    needs: secrets
    secrets: inherit
